version: "3"

services:
  web:
    build: .
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8003"]

  scheduler:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    command: ["python", "-m", "app.script.script"]
